name: file_explorer
description: A basic file explorer made with Flutter
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  mime: ^1.0.1
  flutter_svg: ^1.0.3
  fluentui_system_icons: ^1.1.162

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/icons/

  fonts:
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SF_Pro/SF_Pro_Text_Regular.ttf
    - family: Casper
      fonts:
        - asset: assets/fonts/Casper/Casper-Regular.ttf
